/**
 * MIT License
 * 
 * Copyright (c) 2018 Justin Kunimune
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package main;

import java.io.File;
import java.io.IOException;
import java.util.Locale;
import java.util.logging.Logger;

import main.NumericalMethods.DiscreteFunction;

/**
 * the class where all the math is.
 * 
 * @author Justin Kunimune
 */
public class MRSt {
	
	private static final int x = 0, y = 1, z = 2;
	
	private static final double SPEED_OF_LIGHT = 2.99792458e8;
	private static final double DT_E_N = 14.1; // d-t fusion neutron energy [MeV]
	private static final double DT_T_COEF = .448; // Ti coefficient
	private static final double DT_V_COEF = 5.4e-4; // bulk velocity coefficient
	private static final double DT_RR_COEF = 20.7; // ρR coefficient
	private static final double DT_DS_MIN = 11.8, DT_DS_MAX = 12.9; // [MeV]
	private static final double DT_N_MIN = 13, DT_N_MAX = 15; // [MeV]
	
	private static final int STOPPING_DISTANCE_RESOLUTION = 64;
	private static final double MIN_X = -20, MAX_X = 20; // histogram bounds [cm]
	private static final double MIN_TB = -20, MAX_TB = 80; // histogram bounds [ns]
	private static final double MIN_E = 10.7, MAX_E = 14.2; // histogram bounds [MeV]
	private static final double MIN_TA = 16.0, MAX_TA = 16.5; // histogram bounds [ns]
	private static final double E_RESOLUTION = .1, T_RESOLUTION = 20e-3; // resolutions [MeV], [ns]
	private static final double MAX_SPECTRAL_DENSITY = 1e7; // to save computation time, cap computations when we get this dense
	private static final int MIN_STATISTICS = 1000; // the minimum number of deuterons to define a spectrum at a time

	private static final double[] ENERGY_FIT = {
			1.99467288e-12,  1.42077883e-12,  2.55374768e-12,  3.17744496e-12,
			 -5.55691714e-12, -3.77587508e-11, -5.41468445e-11 }; // energy fit [J/m^i] (this must be extremely precise and would need to be empirically determined
	
	private final double foilDistance; // z coordinate of midplane of foil [m]
	private final double foilThickness; // thickness of foil [m]
	private final double apertureDistance; // distance from TCC to aperture [m]
	private final double apertureWidth; // horizontal dimension of aperture [m]
	private final double apertureHeight; // vertical dimension of aperture [m]
	private final double cosyKmin, cosyKmax; // bounds on deuterons that will be detected by the CSI
	private final double cosyK0, cosyV0, cosyT0, cosyT1; // reference coordinates for beam used by COSY [J], [m/s], [s], [s?]
	private final double focalPlaneAngle; // angle of focal plane [rad]
	private final double[][] cosyCoefficients; // table of coefficients generated by COSY
	private final int[][] cosyExponents; // table of term powers generated by COSY
	private final Particle ion; // either D or P, but probably D

	private final double energyFactor; // conversion factor between neutron and ion energies []
	private final double foilCorrection; // mean energy loss from foil [MeV]
	private final double probHitsFoil; // probability that the neutron goes through the foil
	
	private final DiscreteFunction distanceVsEnergy;
	private final DiscreteFunction energyVsDistance;
	
	private final double[] positionBins; // endpoints of x bins for response function [cm]
	private final double[] timeBBins; // endpoints of time bins for response function [ns]
	private double[][] measuredSpectrum; // measured deuteron counts to go with the position and time-1 bins [1/cm/ns]
	
	private final double[] energyBins; // endpoints of E bins for inferred spectrum [MeV]
	private final double[] timeABins; // endpoints of time bins for inferred spectrum [ns]
	private double[][] inferredSpectrum; // measured deuteron counts to go with the energy and time-0 bins
	
	private final double[] timeAxis; // 1D vectors for higher level measurements [ns]
	private double[] ionTemperature; // [keV]
	private double[] flowVelocity; // [km/s]
	private double[] arealDensity; // [g/cm^2]
	private double[] neutronYield; // [10^15/ns]
	
	private final Logger logger; // for logging
	
	/**
	 * perform some preliminary calculations for the provided configuration.
	 * @param stoppingPower a double[][] containing two columns and n rows. the zeroth column is
	 * the reference values of E in [keV] and the last column is the corresponding values of
	 * dE/dx in [keV/μm].
	 * @param focalTilt angle of the focal plane (0 means untilted) [deg]
	 * @param referenceEnergy minimum ion energy allowed in COSY calculation [eV]
	 * @param referenceEnergy maximum ion energy allowed in COSY calculation [eV]
	 * @param referenceEnergy expected ion energy used in COSY calculation [eV]
	 */
	public MRSt(
			Particle ion, double foilDistance, double foilRadius, double foilThickness,
			double[][] stoppingPowerData,
			double apertureDistance, double apertureWidth, double apertureHeight,
			double minimumEnergy, double maximumEnergy, double referenceEnergy,
			double[][] cosyCoefficients, int[][] cosyExponents,
			double focalTilt, int numBins, Logger logger) {
		this.foilDistance = foilDistance;
		this.foilThickness = foilThickness;
		this.apertureDistance = apertureDistance;
		this.apertureWidth = apertureWidth;
		this.apertureHeight = apertureHeight;
		this.cosyKmin = minimumEnergy*(-Particle.E.charge);
		this.cosyKmax = maximumEnergy*(-Particle.E.charge);
		this.cosyK0 = referenceEnergy*(-Particle.E.charge); // save this in a more useful unit
		this.cosyV0 = Math.sqrt(2*cosyK0/ion.mass); // and get the corresponding speed
		double γ = Math.pow(1 - Math.pow(cosyV0/SPEED_OF_LIGHT, 2), -1/2.);
		double L = (1 + γ)/γ*2*cosyCoefficients[5][4]; // here's a fun shortcut to estimating the length of the lens: first order analysis
		this.cosyT0 = L/cosyV0; // and corresponding time
		this.cosyT1 = -(1+γ)/γ/cosyV0; // and why is time measured in units of distance?
		this.focalPlaneAngle = Math.toRadians(focalTilt);
		this.cosyCoefficients = cosyCoefficients;
		this.cosyExponents = cosyExponents;
		this.ion = ion;
		
		double A = ion.mass/Particle.N.mass;
		this.energyFactor = 4*A/Math.pow(A + 1, 2);
		
		this.foilCorrection = stoppingPowerData[stoppingPowerData.length-1][1]*
				foilThickness/2*1e3; // foil blur width [MeV]
		
		double foilMaxAngle = Math.atan(foilRadius/foilDistance);
		this.probHitsFoil = (1 - Math.cos(foilMaxAngle))/2;
		
		double[] dxdE = new double[stoppingPowerData.length]; // integrate the stopping power to get stopping distance
		double[] E = new double[stoppingPowerData.length];
		for (int i = 0; i < stoppingPowerData.length; i ++) {
			dxdE[i] = 1/(stoppingPowerData[i][1]*1e9*(-Particle.E.charge)); // converting from [GeV/m] to [m/J]
			E[i] = stoppingPowerData[i][0]*1e3*(-Particle.E.charge); // and from [keV] to [J]
		}
		DiscreteFunction distanceVsEnergyRaw = new DiscreteFunction(E, dxdE).antiderivative();
		this.distanceVsEnergy = distanceVsEnergyRaw.indexed(STOPPING_DISTANCE_RESOLUTION);
		this.energyVsDistance = distanceVsEnergyRaw.inv().indexed(STOPPING_DISTANCE_RESOLUTION);
		
		this.positionBins = new double[numBins+1];
		this.timeBBins = new double[numBins+1]; // linearly space the output bins
		for (int i = 0; i <= numBins; i ++) {
			this.positionBins[i] = MIN_X + i*(MAX_X - MIN_X)/numBins;
			this.timeBBins[i] = cosyT0/1e-9 + MIN_TB + i*(MAX_TB - MIN_TB)/numBins;
		}
		this.energyBins = new double[(int) ((MAX_E - MIN_E)/E_RESOLUTION + 1)];
		for (int i = 0; i < energyBins.length; i ++)
			this.energyBins[i] = MIN_E + i*(MAX_E - MIN_E)/(energyBins.length-1);
		this.timeABins = new double[(int) ((MAX_TA - MIN_TA)/T_RESOLUTION + 1)];
		for (int i = 0; i < timeABins.length; i ++)
			this.timeABins[i] = MIN_TA + i*(MAX_TA - MIN_TA)/(timeABins.length-1);
		
		this.timeAxis = new double[timeABins.length-1];
		for (int i = 0; i < timeABins.length-1; i ++)
			this.timeAxis[i] = (this.timeABins[i] + this.timeABins[i+1])/2;
		
		this.logger = logger;
	}
	
	/**
	 * compute the probability that a given neutron released at this energy will spawn an ion
	 * and knock that ion through the aperture.
	 * @param energy energy of the released particles [eV]
	 * @return the fraction of particles that are worth simulating
	 */
	public double efficiency(double energy) {
		double n = 0.08e2; // I'm not sure what units this has or whence it came
		double dσdΩ = 4.3228e3/Math.sqrt(energy) - 0.6523; // same with these ones
		double dΩ = apertureWidth*apertureHeight / Math.pow(apertureDistance - foilDistance, 2);
		double l = foilThickness; // assume the foil is thin so we don't have to worry about multiple collisions
		return probHitsFoil * n*dσdΩ*dΩ*l;
	}
	
	/**
	 * compute the total response to an implosion with the given neutron spectrum.
	 * @param energies the energies that describe the rows of counts [MeV]
	 * @param times the times that describe the columns of counts [ns]
	 * @param spectrum the time- and energy- resolved neutron spectrum in number of neutrons. each
	 * row corresponds to one element of energies, and each column one element of times. [#/MeV/ns]
	 * @return the time- and position- resolved ion spectrum measured at the focal plane. each
	 * row corresponds to one element of this.energyBins, and each column corresponds to one
	 * element of this.timeBins.
	 */
	public void respond(double[] energies, double[] times, double[][] spectrum) {
		if (logger != null) logger.info("beginning Monte Carlo computation.");
		
		int maxSimsPerBin = (int)Math.ceil(MAX_SPECTRAL_DENSITY * // come up with a cap on simulation numbers
				(energies[energies.length-1] - energies[0])/(energies.length-1) *
				(times[times.length-1] - times[0])/(times.length-1)); // assume roughly even spacing so we don't have to keep calculating this
		
		long startTime = System.currentTimeMillis();
		int masterCount = 0;
		
		this.measuredSpectrum = new double[positionBins.length-1][timeBBins.length-1];
		this.inferredSpectrum = new double[energyBins.length-1][timeABins.length-1];
		for (int i = 0; i < energies.length-1; i ++) { // for each input bin
			if (energyFactor*energies[i+1] < cosyKmin/(-Particle.E.charge)/1e6)
				continue; // (skipping those that cannot be useful)
			for (int j = 0; j < times.length-1; j ++) {
				if (spectrum[i][j] > 0) {
					double absSpectrum = spectrum[i][j] *
							(energies[i+1] - energies[i]) * (times[j+1] - times[j]); // convert the spectral value from density to count
					double energy0 = energies[i]*1e6, energy1 = energies[i+1]*1e6;
					double time0 = times[j]*1e-9, time1 = times[j+1]*1e-9; // pull out the bounds, being careful of units
					
					double expNumParticles = absSpectrum*this.efficiency((energy0 + energy1)/2); // read how many particles we should expect
					int numParticles = NumericalMethods.poisson(expNumParticles); // draw the "actual" number of particles from an approximate Poisson distribution
					int numSimulations = (int) Math.min(
							numParticles, Math.pow(maxSimsPerBin, 2)); // but don't go crazy if we don't have to
					double weight = (double) numParticles / numSimulations; // just remember to weigh it properly if you reduce the number of particles
					
					for (int k = 0; k < numSimulations; k ++) {
						double energy = energy0 + Math.random()*(energy1 - energy0); // randomly choose values from the bin
						double time = time0 + Math.random()*(time1 - time0);
						double[] xt = this.simulate(energy, time); // do the simulation!
						double x = xt[0]/1e-2, t1 = xt[1]/1e-9; // then convert to readable units
						if (Double.isNaN(x))	continue; // sometimes, they won't hit the CSI. That's fine.
						
						int xBin = NumericalMethods.coerce(0, positionBins.length-1,
								(x - MIN_X)/(MAX_X - MIN_X)*(positionBins.length-1)); // locate its bin
						int tbBin = NumericalMethods.coerce(0, timeBBins.length-1,
								(t1 - cosyT0/1e-9 - MIN_TB)/(MAX_TB - MIN_TB)*(timeBBins.length-1));
						measuredSpectrum[xBin][tbBin] += weight; // finally, add it to the tally
						
						double[] et = this.backCalculate(xt[0], xt[1]); // now do the back-calculation (using the unconverted values)
						double e = et[0]/(-Particle.E.charge)/1e6, t0 = et[1]/1e-9; // then convert to readable units
						
						int eBin = NumericalMethods.coerce(0, energyBins.length-1,
								(e - MIN_E)/(MAX_E - MIN_E)*(energyBins.length-1));
						int taBin = NumericalMethods.coerce(0, timeABins.length-1,
								(t0 - MIN_TA)/(MAX_TA - MIN_TA)*(timeABins.length-1));
						inferredSpectrum[eBin][taBin] += weight; // add it to the corrected tally, as well
						
						masterCount ++;
					}
				}
			}
		}
		
		analyze();
		
		long endTime = System.currentTimeMillis();
		if (logger != null)
			logger.info(String.format(Locale.US, "completed %d simulations in %.2f minutes.",
					masterCount, (endTime - startTime)/60000.));
	}
	
	/**
	 * simulate a single random neutron emitted from TCC at the given energy and determine the
	 * position and time at which its child ion crosses the focal plane.
	 * @param energy initial energy of released neutron [eV].
	 * @param time initial time of released neutron [s].
	 * @return { signed hypot(x,z), t } [m, s].
	 */
	public double[] simulate(double energy, double time) {
		double[] rCollision = chooseCollisionPosition();
		
		double[] rAperture = chooseAperturePosition();
		
		double[] vFinal = computeFinalVelocity(energy, rCollision, rAperture);
		
		double[] rFocal = computeFocusedPosition(rCollision, vFinal, time);
		
		return new double[] { rFocal[x]/Math.cos(focalPlaneAngle), rFocal[3] };
	}
	
	/**
	 * estimate the original time and energy of this deuteron without looking at its actual
	 * time and energy, by guessing its energy and accounting for travel time.
	 * @param position the position where it hits the focal plane [m]
	 * @param time the time at which it hits the focal plane [s]
	 * @return { energy, time } [J, s].
	 */
	public double[] backCalculate(double position, double time) {
		double focusingDistance = position*Math.sin(focalPlaneAngle);
		double E = 0; // [J]
		for (int i = 0; i < ENERGY_FIT.length; i ++)
			E += ENERGY_FIT[i]*Math.pow(position, i);
		double v = Math.sqrt(2*E/ion.mass);
		double d0 = (E - cosyK0)/cosyK0;
		double lf = cosyPolynomial(4, new double[] {0, 0, 0, 0, 0, d0}); // re-use the COSY mapping to estimate the time of flight from energy
		double timeCorrection = cosyT0 + lf*cosyT1 + focusingDistance/v;
		return new double[] { E, time - timeCorrection };
	}
	
	/**
	 * take the back-calculated spectrum and use it to compute and store time-resolved values
	 * for ion temperature, areal density, and yield.
	 */
	public void analyze() {
		this.ionTemperature = new double[timeAxis.length];
		this.flowVelocity = new double[timeAxis.length];
		this.arealDensity = new double[timeAxis.length];
		this.neutronYield = new double[timeAxis.length];
		
		double[] energy = new double[energyBins.length]; // [MeV]
		for (int i = 0; i < energy.length; i ++)
			energy[i] = energyBins[i]/energyFactor;
		
		for (int i = 0; i < timeAxis.length; i ++) { // at each time
			double[] spectrum = new double[this.inferredSpectrum.length]; // slice out the relevant spectrum
			int statistics = 0;
			for (int j = 0; j < inferredSpectrum.length; j ++) {
				double Ej = (energy[j] + energy[j+1])/2*1e6; // [eV]
				spectrum[j] = this.inferredSpectrum[j][i]/this.efficiency(Ej); // [1]
				statistics += this.inferredSpectrum[j][i];
			}
			
			if (statistics < MIN_STATISTICS) { // don't try to compute these if we have very few deuterons
				this.neutronYield[i] = Double.NaN;
				this.arealDensity[i] = Double.NaN;
				this.flowVelocity[i] = Double.NaN;
				this.ionTemperature[i] = Double.NaN;
				continue;
			}
			
			double primaryYield = NumericalMethods.integral(energy, spectrum, DT_N_MIN, DT_N_MAX);
			this.neutronYield[i] = primaryYield/1e15; // [10^15/ns]
			
			double scatteredYield = NumericalMethods.integral(energy, spectrum, DT_DS_MIN, DT_DS_MAX); // infer total DS yield
			double ratio = scatteredYield/primaryYield;
			this.arealDensity[i] = DT_RR_COEF*ratio; // [g/cm^2]
			
			double mean = NumericalMethods.mean(energy, spectrum); // [MeV]
			mean = mean + foilCorrection; // correct for foil downshift
			this.flowVelocity[i] = (mean - DT_E_N)/DT_V_COEF; // km/s
			System.out.println(mean);
			
			double std = NumericalMethods.std(energy, spectrum); // [MeV]
//			std = Math.sqrt(Math.max(0, std*std - foilCorrection*foilCorrection/3)); // correct for foil broadening TODO: how do I account for V_CM?
			this.ionTemperature[i] = DT_T_COEF/mean*std*std*1e3; // Ti is just a standard deviation [keV]
		}
	}
	
	/**
	 * choose a random location in the foil for the neutron to collide.
	 * @return { x, y, z } [m]
	 */
	private double[] chooseCollisionPosition() {
		double θF = Math.acos(1 - 2*Math.random()*probHitsFoil);
		double rF = foilDistance*Math.tan(θF); // NOTE: original code assumes uniform distribution within foil; I account for nonzero solid angle subtended at TCC.
		double φF = Math.random()*2*Math.PI;
		double zF = foilDistance + (2*Math.random()-1)*foilThickness/2; // assume foil is thin, so every z coordinate is equally likely
		return new double[] { rF*Math.cos(φF), rF*Math.sin(φF), zF };
	}
	
	/**
	 * choose a random location in the aperture plane for the deuteron to pass through.
	 * @return { x, y, z } [m]
	 */
	private double[] chooseAperturePosition() {
		double xA = (2*Math.random()-1)*apertureWidth/2; // assume aperture is far away, so every point in it is equally likely to be hit
		double yA = (2*Math.random()-1)*apertureHeight/2;
		double zA = apertureDistance;
		return new double[] { xA, yA, zA };
	}
	
	/**
	 * compute the velocity with which the deuteron passes through the aperture.
	 * @param vInitial {vx,vy,vz} of the neutron as it enters the foil [m/s].
	 * @param A ratio of charged particle mass to neutron mass.
	 * @param rFoil {x,y,z} of the point at which the neutron strikes the deuteron [m].
	 * @param rAperture {x,y,z} of the point where the deuteron passes through the aperture [m].
	 * @return { vx, vy, vz } [m/s]
	 */
	private double[] computeFinalVelocity(
			double energy, double[] rFoil, double[] rAperture) {
		double E0 = -Particle.E.charge*energy; // convert energy from [eV] to [J]
		
		double[] nHat = { // get the unit vector in the direction of the neutron
				rFoil[x], rFoil[y], rFoil[z] };
		double norm = Math.sqrt(sqr(nHat));
		for (int i = 0; i < 3; i ++)
			nHat[i] /= norm;
		
		double[] dHat = { // and the unit vector in the direction of the ion
				rAperture[0] - rFoil[0], rAperture[1] - rFoil[1], rAperture[2] - rFoil[2] };
		norm = Math.sqrt(sqr(dHat));
		for (int i = 0; i < 3; i ++)
			dHat[i] /= norm;
		
		double cosθ = nHat[x]*dHat[x] + nHat[y]*dHat[y] + nHat[z]*dHat[z];
		double E1 = energyFactor*E0*cosθ*cosθ; // assume elastic collision between neutron and ion
		double distance = (foilDistance + foilThickness/2 - rFoil[2])/dHat[2];
		E1 = energyVsDistance.evaluate(distanceVsEnergy.evaluate(E1) - distance); // lose some energy by dragging through the foil
		
//		System.out.print(E1/Particle.P.charge/1e6+", ");
		
		if (E1 < cosyKmin || E1 > cosyKmax) {
			return new double[] { Double.NaN, Double.NaN, Double.NaN }; // some won't make it through the "energy aperture"
		}
		else {
			double v = Math.sqrt(2*E1/ion.mass); // get the resulting velocity otherwise
			return new double[] { v*dHat[x], v*dHat[y], v*dHat[z] };
		}
	}
	
	/**
	 * evaluate the mapping provided by COSY to obtain the time and position and velocity at
	 * which the ion passes the back reference plane.
	 * @param rFoil {x,y,z} of the point at which the neutron strikes the deuteron [m].
	 * @param vInit {vx,vy,vz} of the deuteron as it exits the foil [m/s]
	 * @param tNeutron the time at which the neutron was released [s].
	 * @return { x, y, z, t } at which it strikes the focal plane [m, m, s]
	 */
	private double[] computeFocusedPosition(double[] rFoil, double[] vInit, double tNeutron) {
		if (Double.isNaN(vInit[0]))
			return new double[] { Double.NaN, Double.NaN, Double.NaN, Double.NaN };
		
		double x0 = rFoil[x], y0 = rFoil[y]; // COSY takes spatial coordinates in [m] (assume foil is thin so we can ignore rFoil[2])
		double a0 = vInit[x]/cosyV0, b0 = vInit[y]/cosyV0; // angular coordinates in [rad] (more or less)
		double t0 = 0; // assume time it takes neutron to hit foil is negligible
		double K0 = 1/2.*ion.mass*sqr(vInit); // for the 'd' coordinate, we must convert velocity to energy
		double d0 = (K0 - cosyK0)/cosyK0; // and then compare that to an expected reference energy
		double[] input = { x0, a0, y0, b0, t0, d0 };
		double[] output = new double[5];
		for (int i = 0; i < output.length; i ++) // the polynomial is pretty simple to compute
			output[i] = cosyPolynomial(i, input);
		double[] rPlane = { output[0], output[2], 0 }; // [m]
		double[] vFinal = { output[1]*cosyV0, output[3]*cosyV0, vInit[z] }; // [m/s]
		double tPlane = tNeutron + cosyT0 + output[4]*cosyT1;
		
		double tFocusing = rPlane[x] / (vFinal[z]/Math.tan(focalPlaneAngle) - vFinal[x]); // finally, account for the additional t that it takes to strike the focal plane
		double[] rFocused = {
				rPlane[x] + tFocusing*vFinal[x],
				rPlane[y] + tFocusing*vFinal[y],
				rPlane[z] + tFocusing*vFinal[z] };
		
		return new double[] { rFocused[x], rFocused[y], rFocused[z], tPlane + tFocusing };
	}
	
	/**
	 * evaluate a single polynomial from that table of coefficients.
	 * @param i the index of the parameter to compute
	 * @param input the initial values to use
	 * @return the final value of parameter i
	 */
	private double cosyPolynomial(int i, double[] input) {
		double output = 0;
		for (int j = 0; j < cosyCoefficients.length; j ++) {
			double term = cosyCoefficients[j][i];
			for (int k = 0; k < input.length; k ++) {
				term *= Math.pow(input[k], cosyExponents[j][k]);
			}
			output += term;
		}
		return output;
	}
	
	public double[] getMeasuredTimeBins() {
		return this.timeBBins;
	}
	
	public double[] getPositionBins() {
		return this.positionBins;
	}
	
	public double[][] getMeasuredSpectrum() {
		return this.measuredSpectrum;
	}
	
	public double[] getInferredTimeBins() {
		return this.timeABins;
	}
	
	public double[] getEnergyBins() {
		return this.energyBins;
	}
	
	public double[][] getInferredSpectrum() {
		return this.inferredSpectrum;
	}
	
	public double[] getTimeAxis() {
		return this.timeAxis;
	}
	
	public double[] getIonTemperature() {
		return this.ionTemperature;
	}
	
	public double[] getFlowVelocity() {
		return this.flowVelocity;
	}
	
	public double[] getArealDensity() {
		return this.arealDensity;
	}
	
	public double[] getNeutronYield() {
		return this.neutronYield;
	}
	
	/**
	 * convert a time-cumulative spectrum, as read from an input file, into an array of count
	 * densities. also, edit energies to make it bin edges. this will remove the last row of
	 * energies. given that the last row is over 29 MeV, I think that's fine.
	 * @param timeAxis the time bin boundaries [ns]
	 * @param energyAxis the energy bin midpoints [MeV]
	 * @param spectrum array of the neutron spectrum integrated in time [#/MeV]
	 * @return spectrum array of the neutron spectrum [#/MeV/ns]
	 */
	public static double[][]
			correctSpectrum(double[] times, double[] energies, double[][] spectrum) {
		for (int i = energies.length-1; i > 0; i --) // start by fixing the energies
			energies[i] = (energies[i-1] + energies[i])/2;
		energies[0] = 2*energies[0] - energies[1]; // for the last one, assume equal spacing
		
		double[][] output = new double[energies.length-1][times.length-1];
		for (int i = 0; i < energies.length-1; i ++) { // now for the spectrum
			for (int j = 0; j < times.length-1; j ++)
				output[i][j] = (spectrum[i][j+1] - spectrum[i][j])/(times[j+1] - times[j]); // you're just taking this derivative
		}
		
		return output;
	}

	/**
	 * @param args
	 * @throws IOException 
	 * @throws NumberFormatException 
	 */
	public static void main(String[] args) throws NumberFormatException, IOException {
		MRSt sim = new MRSt(
				Particle.D, 3.0e-3, 0.3e-3, 80e-6,
				CSV.read(new File("data/stopping_power_deuterons.csv"), ','),
				6e0, 4.0e-3, 20.0e-3, 10.7e6, 14.2e6, 12.45e6,
				CSV.readCosyCoefficients(new File("data/MRSt_IRF_FP tilted.txt"), 3),
//				CSV.readCosyCoefficients(new File("data/MRSt_IRF_FP not tilted.txt"), 3),
				CSV.readCosyExponents(new File("data/MRSt_IRF_FP tilted.txt"), 3), 70.3,
				100, null);
		
		double[][] spectrum = CSV.read(new File("data/nsp_150327_16p26.txt"), '\t');
		double[] timeAxis = CSV.readColumn(new File("data/nsp_150327_16p26_time.txt"));
		double[] energyAxis = CSV.readColumn(new File("data/Energy bins.txt"));
		spectrum = correctSpectrum(timeAxis, energyAxis, spectrum);
		
//		for (int i = 0; i < 216; i ++) {
//			double e0 = 12+Math.random()*5;
//			System.out.print("["+e0+", ");
//			double[] xt = sim.simulate(e0*1e6, 0);
//			System.out.print(xt[0]/1e-2+", ");
//			double[] et = sim.backCalculate(xt[0], xt[1]);
//			double e = et[0]/(-Particle.E.charge)/1e6, t0 = et[1]/1e-9;
//			System.out.println(e+", "+t0+"],");
//		}
		
		sim.respond(energyAxis, timeAxis, spectrum);
	}
	
	/**
	 * square a vector, because this takes so long to write out every time.
	 * @param v
	 * @return
	 */
	private static double sqr(double[] v) {
		double s = 0;
		for (double x: v)
			s += Math.pow(x, 2);
		return s;
	}
	
}
